{% set name = "qp" %}
{% set version = "1.0.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/q/qp-prob/qp_prob-{{ version }}.tar.gz
  sha256: adadaaac3f2a9067a26fcd66bdebeec8a9bf2075601f455dc87b9e00118fcfdf

build:
  number: 0

outputs:
  - name: {{ name }}-prob
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
        - setuptools_scm_git_archive
      run:
        - python >={{ python_min }}
        - numpy >=2.0
        - scipy >=1.7.0
        - tables-io >=1.0.0
        - deprecated
    test:
      requires:
        - python {{ python_min }}
      imports:
        - qp

  - name: {{ name }}-prob-full
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
        - setuptools_scm_git_archive
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('qp-prob', max_pin='x.x.x') }}
        - tables-io-full
        - matplotlib-base
        - pytdigest
        - scikit-learn >=1.0
    test:
      requires:
        - python {{ python_min }}
      imports:
        - qp

  - name: {{ name }}
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
        - setuptools_scm_git_archive
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('qp-prob', max_pin='x.x.x') }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - qp

about:
  home: http://github.com/LSSTDESC/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Quantile parametrization for probability distribution functions.
  description: |
    A python package for handling probability distributions using various parametrizations
  dev_url: https://github.com/LSSTDESC/{{ name }}

extra:
  recipe-maintainers:
    - eacharles
