{% set name = "qp" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LSSTDESC/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d10c7f9efae40e73975b9f0e531ca0ded99ebf7adb721b4ab5c4fc4abd21125d

build:
  number: 0

outputs:
  - name: {{ name }}-prob
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools_scm
        - setuptools_scm_git_archive
      run:
        - python >=3.6
        - numpy
        - scipy >=1.7.0
        - tables-io >=0.8.1
        - deprecated
    test:
      imports:
        - qp

  - name: {{ name }}-prob-full
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('qp-prob', max_pin='x.x.x') }}
        - astropy
        - h5py
        - pandas
        - pyarrow
        - pytables
    test:
      imports:
        - qp
        - astropy
        - h5py
        - pandas
        - pyarrow

  - name: {{ name }}
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('qp-prob', max_pin='x.x.x') }}
        - astropy
        - h5py
        - pandas
        - pyarrow
        - pytables
    test:
      imports:
        - qp
        - astropy
        - h5py
        - pandas
        - pyarrow

about:
  home: http://github.com/LSSTDESC/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Quantile parametrization for probability distribution functions.
  description: |
    A python package for handling probability distributions using various parametrizations
  dev_url: https://github.com/LSSTDESC/{{ name }}

extra:
  recipe-maintainers:
    - eacharles
