{% set name = "qp" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LSSTDESC/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 42bba2a43da109140ba8e07a09996d7710081ec04caacc5052a12746d747ab18

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm <=6.1.0
    - setuptools_scm_git_archive

  run:
    - python >=3.6
    - numpy
    - scipy >=1.7.0
    - matplotlib-base
    - scikit-learn
    - tables-io >=0.7.4

test:
  imports:
    - qp

about:
  home: http://github.com/LSSTDESC/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Quantile parametrization for probability distribution functions.
  description: |
    A python package for handling probability distributions using various parametrizations
  dev_url: https://github.com/LSSTDESC/{{ name }}

extra:
  recipe-maintainers:
    - eacharles
