{% set name = "qp" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LSSTDESC/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7498cd35bfbecf8beac25f75bb3b01a22e0b3f50acbdf8d4aabfb3d45a5f39bb

build:
  number: 1

outputs:
  - name: {{ name }}-prob
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools_scm
        - setuptools_scm_git_archive
      run:
        - python >={{ python_min }}
        - numpy
        - scipy >=1.7.0
        - tables-io >=0.8.1
        - deprecated
    test:
      requires:
        - python {{ python_min }}
      imports:
        - qp

  - name: {{ name }}-prob-full
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('qp-prob', max_pin='x.x.x') }}
        - astropy
        - h5py
        - pandas
        - pyarrow
        - pytables
    test:
      requires:
        - python {{ python_min }}
      imports:
        - qp
        - astropy
        - h5py
        - pandas
        - pyarrow

  - name: {{ name }}
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('qp-prob', max_pin='x.x.x') }}
        - astropy
        - h5py
        - pandas
        - pyarrow
        - pytables
    test:
      requires:
        - python {{ python_min }}
      imports:
        - qp
        - astropy
        - h5py
        - pandas
        - pyarrow

about:
  home: http://github.com/LSSTDESC/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Quantile parametrization for probability distribution functions.
  description: |
    A python package for handling probability distributions using various parametrizations
  dev_url: https://github.com/LSSTDESC/{{ name }}

extra:
  recipe-maintainers:
    - eacharles
